repository: SwedbankPay/swedbank-pay-design-guide-jekyll-theme
plugins:
  - jekyll-contentblocks
  - jekyll-material-icon-tag
  - jekyll-redirect-from
  - jemoji
  - kramdown-plantuml
  - swedbank-pay-design-guide-jekyll-theme
# To include node_modules and other folders that are excluded by default:
exclude:
  - spec
  - lib
  - LICENSE
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - "*.json"
  - "*.gemspec"
  - "*.yml"
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true
    default_lang: html
    css_class: "code-view"
    code_class: "code-view-code"
    table_class: "code-view-table"
    gutter_class: "code-view-numbers"
    block:
      line_numbers: true
      start_line: 1
tipue_search:
  include:
    pages: true
opengraph:
  description: Swedbank Pay Design Guide theme for Jekyll
  image: /image1.png
design_guide:
  base_url: https://design.swedbankpay.com
  version: 5.0.2
search:
  enabled: true
  url:
    default: https://search.developer.stage.swedbankpay.com
    production: https://search.developer.swedbankpay.com
topbar:
  navigation:
    - url: /page1
      title: Top 1
    - url: /page2
      title: Top 2
google_analytics:
  tracking_id: false
defaults:
  - values:
      layout: default
github:
  branch: main
  repository_url: https://github.com/SwedbankPay/swedbank-pay-design-guide-jekyll-theme
