repository: SwedbankPay/swedbank-pay-design-guide-jekyll-theme
plugins:
  - "jekyll-github-metadata"
  - jemoji
# To include node_modules and other folders that are excluded by default:
# exclude: []
tipue_search:
  include:
    pages: true
opengraph:
  description: Swedbank Pay Design Guide theme for Jekyll
  image: /image1.png
design_guide:
  base_url: https://design.swedbankpay.com
  version: 4.3.0
search:
  enabled: true
  url: /search
topbar:
  navigation:
  - url: /page1
    title: Top 1
  - url: /page2
    title: Top 2
google_analytics:
  tracking_id: 
defaults:
  - values:
      layout: default
