name: Jekyll site CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker compose build
      run: |
        docker-compose build
    - name: Docker compose up
      run: |
        docker-compose up
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: kamiazya/setup-graphviz@v1
    - name: Get libfontconfig
      run: |
        sudo apt-get install -y libfontconfig
    - name: Build the site
      run: |
        sudo gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build JEKYLL_ENV=production
